name: build and push Docker Image
on:
  push:
    branches:
      - "master"
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build . --file dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/django-app-jenkinslab

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/django-app-jenkinslab
